### ISSUE TITLE
Duplicate datasets caused by submission error

### ISSUE THREAD

**Issue by Jyouhou** [cvfadmin/COVE#100]
Hi,

This is the author of dataset https://cove.thecvf.com/datasets/822 and https://cove.thecvf.com/datasets/823.

When I submitted the dataset, the webpage prompted `error` and I thought the submission failed, so I tried multiple times. Today I received emails that the datasets have been added. 

Please remove the duplicate one (823). Thanks!

**Comment by craymichael** [comment]
Hello, we are already working on removing this duplicate - apologies for the inconvenience! It will be removed shortly.
