### ISSUE TITLE
Cannot submit dataset

### ISSUE THREAD

**Issue by devavratTomar** [cvfadmin/COVE#115]
Hi, I have been trying to submit the following dataset: 
http://cmictig.cs.ucl.ac.uk/niftyweb/challenge/
with the open access link to the paper: https://doi.org/10.1016/j.neuroimage.2017.03.010

But unfortunately, nothing happens after I click the submit button.

**Comment by craymichael** [comment]
Hi,

I haven't seen this issue before. Here are some things that you can try - let me know if you have any luck!

- Try both Google Chrome and Firefox. Some users have reported issues with Chrome in the past.
- Ensure that you have filled out all required fields. In addition, the URL to the dataset image must end with an image filename (png, jpg, etc.)

If you continue to have issues, let me know and I can sort something out.

**Comment by devavratTomar** [comment]
Hi, thank you for your reply. I tried to submit it with Firefox but the issue still remains the same. The above dataset I am linking requires users to first register via email and then it is made available. There is no direct link to the dataset images.

```
The dataset will be sent to the following e-mail address:

```

**Comment by craymichael** [comment]
No worries about the image, it is optional. I see that other datasets have been submitted since yesterday, so there must be something up. Can you send a screenshot of the filled out dataset form? I can see if there is anything obvious to me that is wrong. If there is not, I will add the dataset manually, and then I can have you transfer ownership to your account.

**Comment by Parskatt** [comment]
I'm having similar issues, getting this:
![image](https://user-images.githubusercontent.com/22053118/227561858-afe290dd-437d-4e8b-b850-549906fbb4e4.png)
"Unknown field" seems worrying. Leaving the field empty doesn't solve the issue.

**Comment by Parskatt** [comment]
I am also somewhat confused, on COVE it says: 
> If you are a researcher who owns a dataset that is not currently in COVE, please help make this site as comprehensive a resource as possible for the community and add it to the database

But in the CVPR camera ready submission, it seemed like we should submit the dataset even if we are not the original authors. The only other option was saying that "no dataset was used":
![image](https://user-images.githubusercontent.com/22053118/227562761-8d6b2ef4-9951-4136-a67f-167e2041c1df.png)

**Comment by craymichael** [comment]
@Parskatt I have seen this issue before. Unfortunately, the only way around this at the moment is to submit your dataset again and do not touch the open access field whatsoever. This field causes unresolved validation problems.

**Comment by Parskatt** [comment]
@craymichael are we encouraged to submit the dataset even as non-owners? In your reply here you are also referring to "your dataset". Just want to clarify that I'm not the author of the dataset but simply used it in a paper, still ok to submit?

**Comment by craymichael** [comment]
@Parskatt The policy of COVE is that only datasets that you own should be submitted.

**Comment by Parskatt** [comment]
@craymichael thanks for the response, I'll ask the organizers about their wording then.

**Comment by devavratTomar** [comment]
I am also confused. So should we upload the dataset to COVE only if we own them? I also used the dataset mentioned in the original issue for my CVPR 23 paper and was asked to submit it to COVE as shared by @Parskatt. I am not the creator of the dataset, but it is publicly available.

**Comment by Parskatt** [comment]
@devavratTomar I tweeted at CVPR here: https://twitter.com/Parskatt/status/1639286685866373121 , no response yet though.

Looking at another camera ready paper I saw that they did not even have to check this, so it seems like this checkbox must have appeared very recently, seems like some kind of miscommunication but I'm a bit anxious to not do anything wrong.

**Comment by craymichael** [comment]
Yes, to confirm, please only upload the dataset if you are the owner. There does seem to be some sort of miscommunication here of COVE policy. Hopefully, the organizers can sort this out soon!
