### ISSUE TITLE
The link to the dataset is no longer valid.

### ISSUE THREAD

**Issue by hh-xiaohu** [cvfadmin/COVE#116]
The Dynamic Scene Dataset For View Synthesis And Depth Estimation cannot be accessed. It is showing an error: "Not Found. The requested URL was not found on this server."

**Comment by craymichael** [comment]
Hi, here is a link to the archived version of the website: https://web.archive.org/web/20221001083054/https://www-users.cse.umn.edu/~jsyoon/dynamic_synth/
