### ISSUE TITLE
Dataset thumbnail image not showing up

### ISSUE THREAD

**Issue by rudrakshkapil** [cvfadmin/COVE#118]
Hi, 

When submitting a dataset I provided a permalink to the .png file hosted on a github repo. 
https://github.com/rudrakshkapil/ShadowSense/blob/7703449ee30e197594171f4134a83848f4cabbd7/dataset.png

The thumbnail is not being read by the website (broken image icon showing). Should I host the image somewhere else? And is it possible to edit the info for the submitted dataset if I do change the image link?

**Comment by craymichael** [comment]
Hi, apologies for the delay. You must specify the true URL which can be found by right-clicking the image and copying the URL. In your case it is `https://raw.githubusercontent.com/rudrakshkapil/ShadowSense/7703449ee30e197594171f4134a83848f4cabbd7/dataset.png`. The link you shared isn't directly to the image. I hope that this clears up any confusion.
