### ISSUE TITLE
Allow users to claim preloaded datasets

### ISSUE THREAD

**Issue by ddehueck** [cvfadmin/COVE#19]

**Comment by ddehueck** [comment]
@haroldfry Do you know what preloaded datasets look like in the database right now? Like are they all owned by admin or have null in place of an owner?

**Comment by Eric4Jiang** [comment]
I think she told me all should be owned by Admin.

**Comment by Eric4Jiang** [comment]
You can just log onto admin and click the "Your datasets" and it lists most of them.

**Comment by Eric4Jiang** [comment]
How should this exactly work? I'm assuming all unclaimed datasets will be owned by the admin. Then when a user tries to claim a dataset, the admin will either give or deny that claim. If accepted, the dataset will change owners from admin to that user.

If we're allowing users to claim, then we should also display who owns the dataset (which I don't think we currently do) right?

**Comment by ddehueck** [comment]
> I'm assuming all unclaimed datasets will be owned by the admin. Then when a user tries to claim a dataset, the admin will either give or deny that claim. If accepted, the dataset will change owners from admin to that user.

Yes this is what I've been thinking

> If we're allowing users to claim, then we should also display who owns the dataset (which I don't think we currently do) right? Then maybe in the future we can think about searching datasets owned by a specific user.

Definitely something to think about. This doesn't seem necessary right now but if we want to start making this site more social then these would be good steps.

**Comment by ddehueck** [comment]
Should be fixed with recent PR: #61
