### ISSUE TITLE
Pagination breaks when user zooms in our out of page.

### ISSUE THREAD

**Issue by ddehueck** [cvfadmin/COVE#22]
cmd +/cmd -

**Proposed Solution: Switch to per page pagination instead of infinite scroll**

**Comment by ddehueck** [comment]
@Eric4Jiang Thoughts on moving to separate pages as opposed to infinite scroll?

**Comment by Eric4Jiang** [comment]
Separate pages are are better. It allows us to find dataset number 1000 much faster then to manually keep scrolling.

**Comment by Eric4Jiang** [comment]
Although this question really only matters on the home page. If you think this to be like Google search, no one ever goes to the last page after a search. They'll just do another search instead.

**Comment by Eric4Jiang** [comment]
So actually, I really don't know which is better haha. We can ask tomorrow.

**Comment by ddehueck** [comment]
Separate pages do allow someone to link to a second page though - not too useful but impossible with infinite scrolling.

May also give insight to #35?

**Comment by Eric4Jiang** [comment]
Maybe. I still don't have any clue for that issue. I can't replicate it on my local.

**Comment by ddehueck** [comment]
Yea some that issue is so strange.

**Comment by ddehueck** [comment]
Switched to prev next pagination in #56
