### ISSUE TITLE
Can't click on tags after first time.

### ISSUE THREAD

**Issue by Eric4Jiang** [cvfadmin/COVE#27]
Replicate:

1) Click 'Tasks' and click 'action detection' to include them in your search. This should add a box with the tag name.
2) Then remove the tag by clicking on that box.
3) Click on 'Tasks' again and try to add 'action detection'. You are able to click on it, but a box with the tag name does not appear.

**Comment by ddehueck** [comment]
Try updating to the most recent version on the master branch.

**Comment by Eric4Jiang** [comment]
Seems like it's been resolved by updating the site.
