### ISSUE TITLE
Dataset pages can't reload on live site.

### ISSUE THREAD

**Issue by Eric4Jiang** [cvfadmin/COVE#28]
Steps to reproduce:

1) Click on any dataset.
2) Refresh
3) Get error 502 Bad Gateway

(Refresh works on my localhost, so it might be a problem with the live site)

**Comment by ddehueck** [comment]
I believe this is related to: https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations

As pointed out here: https://github.com/vuejs-templates/webpack/issues/511

**Comment by ddehueck** [comment]
Need to update ngnix config

```location / {
  try_files $uri $uri/ /index.html;
}```

**Comment by haroldfry** [comment]
Nginx was set that way and the mode was set to 'history'. Error log shows process workers was exiting and rebooting. Will keep working on this.

**Comment by Eric4Jiang** [comment]
Any updates on this issue? I feel this bug is important to fix because it does not allow others to link a dataset directly. The user would have to go on the site and manually search for it.

If I tried to reference a dataset for a paper or to a friend (i.e https://cove.thecvf.com/datasets/151) it won't load.

**Comment by haroldfry** [comment]
nginx settings:
1. *important* nginx proxy settings: don't put https, put http instead
2. add try files after proxy. it's used to locate the template.

**Comment by ddehueck** [comment]
Seemed to be resolved an update to nginx settings
