### ISSUE TITLE
Some datasets are showing twice on the home page.

### ISSUE THREAD

**Issue by Eric4Jiang** [cvfadmin/COVE#35]
For example, if you keep scrolling, you eventually see "Music Video Dataset", "Makeup in the Wild", "Actor and Action Dataset" twice.

If I search for them though, they only appear once.

**Comment by ddehueck** [comment]
@Eric4Jiang Did you ever identify the cause for this bug? Or the ability to replicate consistently?

**Comment by Eric4Jiang** [comment]
Still shows up

**Comment by ddehueck** [comment]
Closing until we can replicate and find it the same bug after #56
