### ISSUE TITLE
Datasets that have not been approved shows us when searched for. 

### ISSUE THREAD

**Issue by Eric4Jiang** [cvfadmin/COVE#42]
Dataset "xxtt" has not been approved yet but when searched for it, it will appear for non-admin users.

**Comment by ddehueck** [comment]
Does this dataset actually show it's is_approved flag as False? Are there any duplicates?

**Comment by Eric4Jiang** [comment]
This happens with any dataset that has been recently submitted but not yet approved. 

When I search the dataset on admin only one shows up. And I know it has is_approved set to false because it gives the option to deny / accept it
