### ISSUE TITLE
please add consistent formatting to the citation field for all entries

### ISSUE THREAD

**Issue by ksaenko** [cvfadmin/COVE#46]
For example : Title, Authors, Venue, Year
Long-Term Recurrent Convolutional Networks for Visual Recognition and Description, Jeffrey Donahue, Lisa Anne Hendricks, Sergio Guadarrama, Marcus Rohrbach, Subhashini Venugopalan, Kate Saenko, Trevor Darrell; The IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2015

**Comment by ddehueck** [comment]
Will be resolved once #48 is merged.
