### ISSUE TITLE
Should have an SSL certificate

### ISSUE THREAD

**Issue by ddehueck** [cvfadmin/COVE#5]
We shouldn't be passing unencrypted data between the client and the backend. We can get a good certificate for free from Let's Encrypt.

See helpful links:
- https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/
- https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04

**Comment by ddehueck** [comment]
@haroldfry Do you think you could take a look at this soon? We should have a certificate before asking people to send sensitive data (passwords, emails, etc.) through the site.

**Comment by haroldfry** [comment]
cool. will work on this today.

**Comment by haroldfry** [comment]
certificate added.
