### ISSUE TITLE
Submitting a Dataset

### ISSUE THREAD

**Issue by Eric4Jiang** [cvfadmin/COVE#58]
Here are a few issues I found with the dataset submission page.

1. When there is an error, be more specific about which field needs to be fixed. (For example, if a user types in a non-integer into the "Year paper dataset was published in*" field, we should explicitly say so so they don't have to look over all their info again).

2. When you submit a non-integer into the "Year paper dataset was published in*" field, an type error occurs and asks you to resubmit. However, if the user specified any new tags they wanted to create for the dataset, these new tags would've been successfully created in that first submission even though it wasn't successful. This causes the next submission you make to have an "tag already exists" error, and stalling out (can't submit again but your dataset ALSO hasn't been submitted). Essentially, the tag shouldn't be created until the submission is completely successful.

3. You can't create a new tag if that new tag is a substring of an existing tag. For example, you can't create a new tag named "Hand" if a tag named "Handbags" already exists.

**Comment by ddehueck** [comment]
1. Is fixed by loading the model through the schema - which works now after upgrading marshmallow version

**Comment by Eric4Jiang** [comment]
Which issue is fixed? All 3?

**Comment by ddehueck** [comment]
@Eric4Jiang Nah, just documenting as I go

**Comment by ddehueck** [comment]
2. Is fixed by validating dataset and new tag data first on the backend. Moved the logic for this to the backend.

**Comment by ddehueck** [comment]
Should be completed with #56 now

**Comment by Eric4Jiang** [comment]
Looks fixed. Closing issue.
