### ISSUE TITLE
registration error

### ISSUE THREAD

**Issue by bald6354** [cvfadmin/COVE#62]
I'm getting a post error 500 when I try to register as a new user.

**Comment by ddehueck** [comment]
Thanks for letting us know, we will update this thread as we figure this out.

**Comment by ddehueck** [comment]
@bald6354 We have identified the issue and will push a fix soon.

**Comment by ddehueck** [comment]
@bald6354 It is now working! Please let us know if you are able to register and we will close this issue.

**Comment by bald6354** [comment]
Success! Thanks!
