### ISSUE TITLE
cannot upload dataset

### ISSUE THREAD

**Issue by bald6354** [cvfadmin/COVE#66]
I've typed in the dataset data twice and hit the submit button, but nothing happens.

**Comment by ddehueck** [comment]
If you're using chrome could you go the "Add A Dataset" page after trying to submit and right click and select "Inspect" the "console" and copy and paste any errors you see there to here?

We have not been able to replicate on our end so we appreciate the help.

**Comment by bald6354** [comment]
I figured it out. There is a little red error that popped up next to my image.

![Capture](https://user-images.githubusercontent.com/5856176/77348537-ffb1c980-6d0f-11ea-991a-3a2520221539.PNG)
