### ISSUE TITLE
how to add my dataset?

### ISSUE THREAD

**Issue by prashnani** [cvfadmin/COVE#75]
I am trying to add a dataset proposed in my CVPR 2018 paper (https://github.com/prashnani/PerceptualImageError/blob/master/dataset/dataset_README.md) to COVE. But, selecting "Add a dataset" leads to `Error: Request failed with status code 500`.

**Comment by craymichael** [comment]
Hello, thanks a lot for reporting this issue. We have fixed this issue on the website. Do you mind trying to upload your dataset again? Please let us know if you have issues.
