### ISSUE TITLE
Adding other people's datasets; info on COVE front page

### ISSUE THREAD

**Issue by NikolausDemmel** [cvfadmin/COVE#78]
For the CVPR camera-ready submission, the form includes a question about use of datasets and and COVE.

> The Computer Vision Foundation (CVF) maintains a repository exchange of computer vision datasets (COVE). If your paper uses a dataset that isn't in the archive, you are strongly advised to add it to the CVF repository by using the "Add a Dataset" link at the top of the COVE page (https://cove.thecvf.com/). Please select one of the following options:
>
> [ ] I have submitted (or will submit) the dataset to the CVF repository.
> [ ] The dataset is already available on the CVF repository.
> [ ] The dataset is private and/or sensitive and not available for release.
> [ ] No dataset was used for this paper.

Since there is no option like "I'm using someone else's dataset, but it is not yet on the CVF repository", I'm concluding that you want people to also submit datasets authored by someone else (and not just your own datasets). 

Could you please confirm that this is the case?

Maybe it would be good, if the COVE page itself would somehow explain a bit more what the database is about, who is behind the initiative, and who is supposed to add which datasets, including mention of adding third-party authored datasets. This could also be in form of an FAQ.

Currently, the only info on the entire COVE page that I can find is on the front page:

> COVE is an online repository for computer vision datasets sponsored by the Computer Vision Foundation. It is intended to aid the computer vision research community and serve as a centralized reference for all datasets in the field. If you are a researcher with a dataset not currently in COVE, please help make this site as comprehensive a resource as possible for the community and add it to the database!

"If you are a researcher with a dataset not currently in COVE" sounds to me like you are talking only about people's own (i.e, authored) datasets.

Overall, I must admit that I find this a little terse for making people trust and embrace a platform (which I personally have never before heard of).

PS: Concretely, the dataset I use is this one: https://grail.cs.washington.edu/projects/bal/

**Comment by craymichael** [comment]
Thanks for bringing this to our attention. With COVE, our policy is that only the dataset owner should upload the dataset. We will update the text to reflect this and link to the CVF website to provide some more information about our organization.

**Comment by NikolausDemmel** [comment]
Ok, thanks. 

PS: Then CVPR should consider changing their wording and the options for next year's camera ready submission form, since they seem to encourage adding other people's datasets. (Or maybe that's what you already meant by "We will update the text to reflect this", then forget what I said...)

**Comment by craymichael** [comment]
Yes, we will make sure that the policy is clear between the CVPR dataset form and the COVE website.
