### ISSUE TITLE
Unknown field when adding dataset

### ISSUE THREAD

**Issue by uakfdotb** [cvfadmin/COVE#88]
I get an "Unknown field" error next to "OpenAccess Link to paper" when adding a dataset. This happens both when I leave the field blank, and when I enter a URL to an Open Access paper.

**Comment by craymichael** [comment]
Hi, I just tried to reproduce your issue without success. Do you mind creating a new dataset without touching the "Open Access link" field at all?

**Comment by uakfdotb** [comment]
Thanks, I'm not sure what happened the first time, it worked now.

**Comment by yuliangguo** [comment]
> Hi, I just tried to reproduce your issue without success. Do you mind creating a new dataset without touching the "Open Access link" field at all?

I am facing the same issue at this moment. When the openaccess of a conference is newly online, would COVE take some time to recognize the url?

**Comment by craymichael** [comment]
Hi, would you mind trying to upload the dataset again without touching that field? I recall that this field is problematic and should be left alone. Thanks for your patience.

**Comment by yuliangguo** [comment]
Thanks for the quick response. Unfortunately, either leaving it blank or
filling it with the url triggers the same issue from my end. I seem not
able to find a working trick to submit.

**Comment by craymichael** [comment]
Hi, this is even with uploading a new dataset starting from scratch? If so, please tell me your web browser, dataset details, and username. I can add it for you if you continue to have trouble.


-------- Original message --------
From: Yuliang Guo ***@***.***>
Date: 1/4/22 3:09 PM (GMT-05:00)
To: cvfadmin/COVE ***@***.***>
Cc: Zachariah Carmichael ***@***.***>, Comment ***@***.***>
Subject: Re: [cvfadmin/COVE] Unknown field when adding dataset (#88)


Thanks for the quick response. Unfortunately, either leaving it blank or
filling it with the url triggers the same issue from my end. I seem not
able to find a working trick to submit.

**Comment by yuliangguo** [comment]
Thanks, you have reminded me about the browser. My submission previously
from chrome did not work, but now works on Firefox.

**Comment by craymichael** [comment]
That is good to know. Thank you!


-------- Original message --------
From: Yuliang Guo ***@***.***>
Date: 1/4/22 3:40 PM (GMT-05:00)
To: cvfadmin/COVE ***@***.***>
Cc: Zachariah Carmichael ***@***.***>, Comment ***@***.***>
Subject: Re: [cvfadmin/COVE] Unknown field when adding dataset (#88)


Thanks, you have reminded me about the browser. My submission previously
from chrome did not work, but now works on Firefox.
