### ISSUE TITLE
"Not a valid integer." error whatever i write into "Year paper dataset was published in*"

### ISSUE THREAD

**Issue by fabbrimatteo** [cvfadmin/COVE#93]

**Comment by craymichael** [comment]
Hi, please try the following options to get your dataset submitted-
1. Try creating a new dataset and entering the fields in again
2. Try using a different browser - try both FireFox and Chrome

If you continue to have issues, please send a screenshot of your form and the error message. Thanks!

**Comment by fabbrimatteo** [comment]
Fixed. Thanks!
