### ISSUE TITLE
"OpenAccess Link to Paper" field displays "Unknown Field" which prevents any datasets from being submitted

### ISSUE THREAD

**Issue by rowanz** [cvfadmin/COVE#96]
hi there,

thanks for your great work! when trying to submit a dataset though, the submission doesn't seem to go through. The validation seems stuck on the field "OpenAccess Link to paper" -- when clicking submit, all that happens is that "Unknown Field" pops up there.

I tried this on both firefox and chrome, but couldn't end up submitting anything.

**Comment by craymichael** [comment]
Hi,

We appreciate your nice words! Sorry to hear about this issue - here is what I suggest trying:

1. Create a brand new data set submission
2. Fill out every field but take care to *not* touch the "Open Access" field (i.e., do not type/paste content or click the field at all)
3. Submit the data set
4. Try these steps on both Firefox and Chrome again

There is far better luck on Firefox for this issue. If you continue to have problems, just post the data set details here (and your COVE username) and I can add the data set for you!

**Comment by rowanz** [comment]
It works! Thanks so much @craymichael - indeed, I had to explicitly not touch that field whatsoever. I tested it on Firefox (but I imagine it works on Chrome too).

**Comment by craymichael** [comment]
I am glad to hear it! I appreciate the feedback on the issue as well. :partying_face:
