### ISSUE TITLE
How to update the dataset submitted to COVE?

### ISSUE THREAD

**Issue by CCYChongyanChen** [cvfadmin/COVE#97]
Hi there, I would like to update the thumbnail for the dataset I submitted to COVE. How could I do it? Also, I would like to update the link to the paper afterward but cannot find the right place to do that.
Thank you!

**Comment by craymichael** [comment]
Hi,

To update the thumbnail for a dataset, go to the URL of your dataset `https://cove.thecvf.com/datasets/<number>`, click **Edit Dataset Profile**, then change the field **Thumbnail image link** to your desired image. Be careful _not_ to touch the other fields for now.

Right now, there is no working field just for a paper link. The field "OpenAccess Link to paper" exists, but do not use it as it will cause problems with your dataset. You can always update the "Description of dataset" field instead and make sure that the "Citation Fields" are set correctly.

**Comment by CCYChongyanChen** [comment]
Thank you for your quick reply. 
It seems that the URL you shared doesn't have a button to edit the dataset profile:
![image](https://user-images.githubusercontent.com/21120604/160497375-0ce84a08-02ab-4774-8f7b-7166f97d9dea.png)
Here is what I saw for our dataset page
![image](https://user-images.githubusercontent.com/21120604/160497414-3b5e6354-f712-44e8-a460-4d66ab804162.png)

**Comment by craymichael** [comment]
Hi,

My apologies, I edited my previous response - that link was meant to be slightly different. And this means that you do not own this dataset, at least with the account you are currently signed in with. Whoever is the dataset owner will need to make this change.

**Comment by craymichael** [comment]
Actually, can you try checking the page again? I have approved the dataset, which may have been preventing you from seeing the edit option if you are the dataset owner.

**Comment by CCYChongyanChen** [comment]
Thank you for your quick reply again.
I am the owner of this dataset:
![image](https://user-images.githubusercontent.com/21120604/160499210-61a10e77-0524-4822-9b19-4b16e3e533a4.png)
However, I still cannot see the edit option. I have refreshed the page several times.

![image](https://user-images.githubusercontent.com/21120604/160499317-246f7c1d-df68-4196-8958-0cded2155ad7.png)

**Comment by craymichael** [comment]
Hi,

Please let me know if this URL works: https://cove.thecvf.com/datasets/808/edit

If not, please send me the URL of the thumbnail image and I can make the edit for the dataset. Thanks!

**Comment by CCYChongyanChen** [comment]
That works！ Thanks!
