### ISSUE TITLE
Unable to modify a submitted dataset

### ISSUE THREAD

**Issue by chrockey** [cvfadmin/COVE#99]
Hi!

I am trying to modify a submitted dataset to fix my fool mistake: wrongly typing the year of publication not the title of the paper :(.
The submitted dataset is "ScanNet", which is very popular but missing in the COVE repository.
How can I modify the submitted dataset?

**Comment by craymichael** [comment]
Hi,

The dataset is approved and you can edit the dataset (if you have ownership) at the URL https://cove.thecvf.com/datasets/513/edit

Please let us know if you have more questions!
